### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by FlatBartender** [IssouProjects/project-tube#11]
Define the interface of the network part and proposer a draft of the internal architecture.

- Client/server architecture
- TCP IP communication between two modules, transferring game data
- Create a server class, with client represented as data streams

## Todo
- [x] Multi-thread client server
- [x] Send one way simple data
- [ ] Send one way serialized objects
- [ ] Exchange serialized objects between client and server

## Additional notes
- CMake that builds to executables, the client and server
- The server will have two threads for receiving and sending data
- Implement an abstract class for serialisable objects for serialize et deserialize methods
